//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternationalOnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TxnId { get; set; }
        public string CardNo { get; set; }
        public Nullable<int> TxnAmount { get; set; }
        public Nullable<int> Availability { get; set; }
        public Nullable<int> UsedAcount { get; set; }
        public Nullable<bool> Key { get; set; }
        public Nullable<bool> PayCard { get; set; }
    
        public virtual Card Card { get; set; }
    }
}
